### ISSUE TITLE
Notebook inside a hidden directory not working

### ISSUE THREAD

**Issue by ametis70** [zk-org/zk#271]
I started using `zk` today on Linux with:
```
zk init "$HOME/.notes"
export ZK_NOTEBOOK_DIR="$HOME/.notes"
```
and then I created some notes with `new` and `edit --interactive`. After that, I found out that the `list` and `edit` commands couldn't find any note, even if the files were created correctly. I also tried with `index` without success.

After that, I moved the `$HOME/.notes` directory to `$HOME/Documents/Notes` and the commands now work correctly, so I believe there's a problem with the notebook being in a hidden directory

**Comment by mickael-menu** [comment]
By design, [hidden files and directories are ignored from the `zk` index](https://github.com/mickael-menu/zk/blob/9d882451027b3e847cd6a6878d300e146387c6bb/internal/util/paths/walk.go#L24). Looks like this filter applies to the root notebook directory as well.

Until this is fixed, you can nest your notebook inside a hidden directory, e.g. `~/.notes/notebook`.

**Comment by ametis70** [comment]
Alright, thanks!

**Comment by tjex** [comment]
@ametis70 good to go :) Hope you're still using zk!
