### ISSUE TITLE
Switch to Pretty Upstream

### ISSUE THREAD

**Issue by mcDevnagh** [zk-org/zk#380]
ZK currently uses its own [fork of pretty](https://github.com/zk-org/pretty). This dependency is only used for ouputting tests results. I would like an investigation of all of the implications of the change, which I will document here

**Comment by tjex** [comment]
@mcDevnagh any further thoughts on this? (I'm also back from holidays, feeling refreshed. Lets goooo 💪)

**Comment by tjex** [comment]
@mcDevnagh I had a quick look at this and our fork has [one commit from Mickael](https://github.com/kr/pretty/commit/eea0e240a2d5cb89dc13219ee3cd9c141cac5e25), which adds some pretty printing for `time.Time`. I tested some failing tests with `kr/pretty` and couldn't spot any difference. But I'm sure I must've just missed where this commit is being useful. 

Considering the upstream `kr/pretty` doesn't have any implementation for `time.Time` formatting (so it's not a case where Mickael committed to his branch first in order to make a PR upstream), perhaps it's better to stay with our fork and look at merging upstream instead?

**Comment by mcDevnagh** [comment]
I wouldn't expect https://github.com/kr/pretty to accept, seeing that it hasn't seen a commit in 2 years, and its issues/PRs are ignored. Mickael's fork was added here: https://github.com/zk-org/zk/commit/0e8ae934507ad4eab040860bf80fbaf650c6e4fa Until kr/pretty sees movement again, I think we should stick with our own fork. If that project is dead, there is not a compelling reason to switch back to it.
